# This playbook:
  # renders Jinja template
  # saves per-device config locally
  #does NOT touch network devices



- name: Generate Cisco configs locally
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Render configuration file
      ansible.builtin.template:
        src: templates/base_config.j2
        dest: "rendered/{{ inventory_hostname }}.cfg"